run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Baseline correctness checks
    - govet # baseline correctness checks; you pretty much always want this.
    - staticcheck # a very strong, modern static analyzer; worth the extra CPU.
    - errcheck # Go code often ignores errors; this keeps you honest.
    - ineffassign # catches variables assigned but never used (often real bugs).
    - nilerr # returns nil after checking an error is non-nil? That's suspicious.

    # Style and maintainability checks
    - revive # configurable style / best practices; good replacement for golint.
    - gocritic # lots of bug + perf + style checks; you can tune which diagnostics you care about.
    - misspell # finds commonly misspelled English words.
    - unconvert # removes unnecessary type conversions.

    # Formatting checks
    - goimports # checks code formatting and import statements.

    # Security
    - gosec # inspects source code for security problems.

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    check-type-assertions: true
    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    check-blank: false

  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers if needed
    disable:
      - shadow # Reports variables that shadow other variables - can be too noisy

  goimports:
    # Put imports beginning with prefix after 3rd-party packages
    local-prefixes: github.com/naurffxiv/clearingway

  misspell:
    locale: US
    ignore-words:
      - clearingway
      - naur
      - ffxiv
      - discord
      - fflogs
      - lodestone
      - util

  revive:
    # Enable all rules by default and disable specific ones
    rules:
      # Disabled rules (too noisy or opinionated for most codebases)
      - name: add-constant
        disabled: true
      - name: argument-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: function-result-limit
        disabled: true

  gosec:
    # To select a subset of rules to run, specify them here
    # All available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G104 # Audit errors not checked (errcheck does this better)
      - G307 # Deferring unsafe method - can be too noisy

  gocritic:
    # Enable multiple checks by tags
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - ifElseChain
      - hugeParam # Can be noisy
      - rangeValCopy # Can be noisy

issues:
  # Skip specific files from linting (useful during refactoring)
  exclude-files:
    # Skip old clearingway package files during refactor
    - main\.go
    - internal/clearingway/.*\.go
    - internal/discord/.*\.go
    - internal/fflogs/.*\.go
    - internal/ffxiv/.*\.go
    - internal/lodestone/.*\.go
    - internal/util/.*\.go

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Make issues output unique by line
  uniq-by-line: true

  # Exclude common issues that are often false positives or not critical
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Exclude known linters from partially hard-vendored code
    - path: internal/hmac/
      linters:
        - gosec

    # Exclude shadowing of err variable
    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    # Exclude false positives on context.TODO()
    - linters:
        - gocritic
      text: 'context.TODO'

  # Show all issues
  exclude-use-default: false

  # Independently of option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  exclude-case-sensitive: false

output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate
  formats:
    - format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name in the end of issue text
  print-linter-name: true

  # Sort results by: filepath, line and column
  sort-results: true
